import type { Lead, TableColumnConfig } from "@/types";

export const LEAD_STATUSES = [
  { value: "rejected", label: "Rejected" },
  { value: "booked", label: "Booked" },
  { value: "closed", label: "Closed" },
  { value: "voicemail", label: "Voicemail" },
  { value: "open", label: "Open" },
  { value: "waiting", label: "Waiting" },
  { value: "does-not-exist", label: "Does not exist" },
  { value: "waiting-plus", label: "Strong" },
] as const;

export const CATEGORIES = [
  { value: "restaurant", label: "Restaurant" },
  { value: "retail", label: "Retail" },
  { value: "healthcare", label: "Healthcare" },
  { value: "technology", label: "Technology" },
  { value: "real-estate", label: "Real Estate" },
  { value: "education", label: "Education" },
  { value: "finance", label: "Finance" },
  { value: "hospitality", label: "Hospitality" },
  { value: "automotive", label: "Automotive" },
  { value: "beauty", label: "Beauty & Wellness" },
] as const;

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    businessName: "Bella Vista Restaurant",
    category: "restaurant",
    location: "New York, NY",
    email: "info@bellavista.com",
    phone: "(212) 555-0101",
    website: "www.bellavista.com",
    address: "123 Main St, New York, NY 10001",
    description: "Italian fine dining restaurant",
  },
  {
    id: "2",
    businessName: "Tech Solutions Inc",
    category: "technology",
    location: "San Francisco, CA",
    email: "contact@techsolutions.com",
    phone: "(415) 555-0202",
    website: "www.techsolutions.com",
    address: "456 Market St, San Francisco, CA 94102",
    description: "Enterprise software solutions",
  },
  {
    id: "3",
    businessName: "Green Leaf Medical Center",
    category: "healthcare",
    location: "Los Angeles, CA",
    email: "info@greenleafmedical.com",
    phone: "(310) 555-0303",
    website: "www.greenleafmedical.com",
    address: "789 Sunset Blvd, Los Angeles, CA 90028",
    description: "Primary care and specialty services",
  },
  {
    id: "4",
    businessName: "Urban Fashion Boutique",
    category: "retail",
    location: "Chicago, IL",
    email: "hello@urbanfashion.com",
    phone: "(312) 555-0404",
    website: "www.urbanfashion.com",
    address: "321 State St, Chicago, IL 60601",
    description: "Trendy clothing and accessories",
  },
  {
    id: "5",
    businessName: "Coastal Realty Group",
    category: "real-estate",
    location: "Miami, FL",
    email: "info@coastalrealty.com",
    phone: "(305) 555-0505",
    website: "www.coastalrealty.com",
    address: "654 Ocean Dr, Miami, FL 33139",
    description: "Luxury real estate services",
  },
  {
    id: "6",
    businessName: "Metro Auto Repair",
    category: "automotive",
    location: "Houston, TX",
    email: "service@metroauto.com",
    phone: "(713) 555-0606",
    website: "www.metroauto.com",
    address: "987 Highway 59, Houston, TX 77002",
    description: "Full-service auto repair shop",
  },
  {
    id: "7",
    businessName: "Zen Spa & Wellness",
    category: "beauty",
    location: "Seattle, WA",
    email: "bookings@zenspa.com",
    phone: "(206) 555-0707",
    website: "www.zenspa.com",
    address: "147 Pine St, Seattle, WA 98101",
    description: "Holistic wellness and spa services",
  },
  {
    id: "8",
    businessName: "Downtown Diner",
    category: "restaurant",
    location: "Boston, MA",
    email: "info@downtowndiner.com",
    phone: "(617) 555-0808",
    website: "www.downtowndiner.com",
    address: "258 Tremont St, Boston, MA 02116",
    description: "Classic American diner",
  },
  {
    id: "9",
    businessName: "City Bank & Trust",
    category: "finance",
    location: "New York, NY",
    email: "contact@citybank.com",
    phone: "(212) 555-0909",
    website: "www.citybank.com",
    address: "741 Wall St, New York, NY 10005",
    description: "Personal and business banking",
  },
  {
    id: "10",
    businessName: "Learning Academy",
    category: "education",
    location: "Austin, TX",
    email: "admissions@learningacademy.com",
    phone: "(512) 555-1010",
    website: "www.learningacademy.com",
    address: "852 Congress Ave, Austin, TX 78701",
    description: "Private K-12 education",
  },
  {
    id: "11",
    businessName: "Grand Hotel",
    category: "hospitality",
    location: "Las Vegas, NV",
    email: "reservations@grandhotel.com",
    phone: "(702) 555-1111",
    website: "www.grandhotel.com",
    address: "159 Las Vegas Blvd, Las Vegas, NV 89101",
    description: "Luxury hotel and casino",
  },
  {
    id: "12",
    businessName: "Pizza Corner",
    category: "restaurant",
    location: "Chicago, IL",
    email: "orders@pizzacorner.com",
    phone: "(312) 555-1212",
    website: "www.pizzacorner.com",
    address: "963 Wacker Dr, Chicago, IL 60601",
    description: "Authentic Italian pizza",
  },
  {
    id: "13",
    businessName: "Sunrise Café",
    category: "restaurant",
    location: "San Francisco, CA",
    email: "hello@sunrisecafe.com",
    phone: "(415) 555-1300",
    website: "www.sunrisecafe.com",
    address: "88 Valencia St, San Francisco, CA 94110",
    description: "Breakfast and brunch spot",
  },
  {
    id: "14",
    businessName: "Cloud Nine Software",
    category: "technology",
    location: "Austin, TX",
    email: "sales@cloudnine.io",
    phone: "(512) 555-1400",
    website: "www.cloudnine.io",
    address: "500 Congress Ave, Austin, TX 78701",
    description: "SaaS and cloud infrastructure",
  },
  {
    id: "15",
    businessName: "Pacific Medical Group",
    category: "healthcare",
    location: "San Francisco, CA",
    email: "info@pacificmedical.com",
    phone: "(415) 555-1500",
    website: "www.pacificmedical.com",
    address: "100 Sutter St, San Francisco, CA 94104",
    description: "Multi-specialty medical practice",
  },
  {
    id: "16",
    businessName: "Marshall Electronics",
    category: "retail",
    location: "Houston, TX",
    email: "support@marshallelectronics.com",
    phone: "(713) 555-1600",
    website: "www.marshallelectronics.com",
    address: "1200 Westheimer Rd, Houston, TX 77006",
    description: "Consumer electronics and gadgets",
  },
  {
    id: "17",
    businessName: "Summit Real Estate",
    category: "real-estate",
    location: "Denver, CO",
    email: "listings@summitrealty.com",
    phone: "(303) 555-1700",
    website: "www.summitrealty.com",
    address: "1600 Broadway, Denver, CO 80202",
    description: "Mountain and urban properties",
  },
  {
    id: "18",
    businessName: "Quick Lube Plus",
    category: "automotive",
    location: "Phoenix, AZ",
    email: "appointments@quicklubeplus.com",
    phone: "(602) 555-1800",
    website: "www.quicklubeplus.com",
    address: "3500 E Indian School Rd, Phoenix, AZ 85018",
    description: "Oil change and basic maintenance",
  },
  {
    id: "19",
    businessName: "Serenity Day Spa",
    category: "beauty",
    location: "Los Angeles, CA",
    email: "book@serenitydayspa.com",
    phone: "(310) 555-1900",
    website: "www.serenitydayspa.com",
    address: "450 N Rodeo Dr, Beverly Hills, CA 90210",
    description: "Luxury spa and massage",
  },
  {
    id: "20",
    businessName: "First National Credit Union",
    category: "finance",
    location: "Chicago, IL",
    email: "member@firstnationalcu.org",
    phone: "(312) 555-2000",
    website: "www.firstnationalcu.org",
    address: "200 S LaSalle St, Chicago, IL 60604",
    description: "Community credit union",
  },
  {
    id: "21",
    businessName: "Riverside Language School",
    category: "education",
    location: "Miami, FL",
    email: "enroll@riversidelanguages.com",
    phone: "(305) 555-2100",
    website: "www.riversidelanguages.com",
    address: "200 Biscayne Blvd, Miami, FL 33132",
    description: "Language immersion programs",
  },
  {
    id: "22",
    businessName: "Boutique Inn",
    category: "hospitality",
    location: "Boston, MA",
    email: "stay@boutiqueinn.com",
    phone: "(617) 555-2200",
    website: "www.boutiqueinn.com",
    address: "100 Charles St, Boston, MA 02114",
    description: "Boutique bed and breakfast",
  },
  {
    id: "23",
    businessName: "Sushi Haven",
    category: "restaurant",
    location: "Los Angeles, CA",
    email: "reservations@sushihaven.com",
    phone: "(323) 555-2300",
    website: "www.sushihaven.com",
    address: "8900 Wilshire Blvd, Beverly Hills, CA 90211",
    description: "Japanese sushi and sashimi",
  },
  {
    id: "24",
    businessName: "DataDrive Analytics",
    category: "technology",
    location: "Seattle, WA",
    email: "info@datadrive.io",
    phone: "(206) 555-2400",
    website: "www.datadrive.io",
    address: "400 Broad St, Seattle, WA 98109",
    description: "Business intelligence and analytics",
  },
  {
    id: "25",
    businessName: "Valley General Hospital",
    category: "healthcare",
    location: "Phoenix, AZ",
    email: "info@valleygeneral.org",
    phone: "(602) 555-2500",
    website: "www.valleygeneral.org",
    address: "1200 S 5th Ave, Phoenix, AZ 85003",
    description: "Full-service community hospital",
  },
  {
    id: "26",
    businessName: "Home & Garden Store",
    category: "retail",
    location: "Denver, CO",
    email: "orders@homegardenstore.com",
    phone: "(303) 555-2600",
    website: "www.homegardenstore.com",
    address: "7800 E Colfax Ave, Denver, CO 80220",
    description: "Furniture and garden supplies",
  },
  {
    id: "27",
    businessName: "Lakeside Properties",
    category: "real-estate",
    location: "Seattle, WA",
    email: "info@lakesideproperties.com",
    phone: "(206) 555-2700",
    website: "www.lakesideproperties.com",
    address: "600 Pine St, Seattle, WA 98101",
    description: "Waterfront and lakefront listings",
  },
  {
    id: "28",
    businessName: "Premier Auto Sales",
    category: "automotive",
    location: "Miami, FL",
    email: "sales@premierautosales.com",
    phone: "(305) 555-2800",
    website: "www.premierautosales.com",
    address: "1900 NW 82nd Ave, Miami, FL 33126",
    description: "New and certified pre-owned vehicles",
  },
  {
    id: "29",
    businessName: "Glow Skin Studio",
    category: "beauty",
    location: "New York, NY",
    email: "appointments@glowskinstudio.com",
    phone: "(212) 555-2900",
    website: "www.glowskinstudio.com",
    address: "250 W 57th St, New York, NY 10107",
    description: "Facials and skin treatments",
  },
  {
    id: "30",
    businessName: "Meridian Investment Advisors",
    category: "finance",
    location: "San Francisco, CA",
    email: "clients@meridianadvisors.com",
    phone: "(415) 555-3000",
    website: "www.meridianadvisors.com",
    address: "555 California St, San Francisco, CA 94104",
    description: "Wealth management and planning",
  },
  {
    id: "31",
    businessName: "STEM Prep Academy",
    category: "education",
    location: "Houston, TX",
    email: "admissions@stemprepacademy.com",
    phone: "(713) 555-3100",
    website: "www.stemprepacademy.com",
    address: "1600 Smith St, Houston, TX 77002",
    description: "STEM-focused tutoring and camps",
  },
  {
    id: "32",
    businessName: "Desert Resort & Spa",
    category: "hospitality",
    location: "Phoenix, AZ",
    email: "reservations@desertresort.com",
    phone: "(602) 555-3200",
    website: "www.desertresort.com",
    address: "4925 N Scottsdale Rd, Scottsdale, AZ 85251",
    description: "Luxury desert resort",
  },
  {
    id: "33",
    businessName: "Taco Fiesta",
    category: "restaurant",
    location: "Austin, TX",
    email: "catering@tacofiesta.com",
    phone: "(512) 555-3300",
    website: "www.tacofiesta.com",
    address: "1500 Lavaca St, Austin, TX 78701",
    description: "Tex-Mex and street tacos",
  },
  {
    id: "34",
    businessName: "SecureNet Systems",
    category: "technology",
    location: "Boston, MA",
    email: "sales@securenetsystems.com",
    phone: "(617) 555-3400",
    website: "www.securenetsystems.com",
    address: "1 Cambridge Center, Cambridge, MA 02142",
    description: "Cybersecurity and compliance",
  },
  {
    id: "35",
    businessName: "Family Dental Care",
    category: "healthcare",
    location: "Denver, CO",
    email: "appointments@familydentalcare.com",
    phone: "(303) 555-3500",
    website: "www.familydentalcare.com",
    address: "1700 Broadway, Denver, CO 80290",
    description: "General and cosmetic dentistry",
  },
  {
    id: "36",
    businessName: "Vintage Threads",
    category: "retail",
    location: "Seattle, WA",
    email: "info@vintagethreads.com",
    phone: "(206) 555-3600",
    website: "www.vintagethreads.com",
    address: "1522 10th Ave, Seattle, WA 98122",
    description: "Vintage and consignment clothing",
  },
  {
    id: "37",
    businessName: "Urban Lofts Realty",
    category: "real-estate",
    location: "New York, NY",
    email: "listings@urbanlofts.com",
    phone: "(212) 555-3700",
    website: "www.urbanlofts.com",
    address: "250 Park Ave S, New York, NY 10003",
    description: "Downtown loft and condo specialists",
  },
  {
    id: "38",
    businessName: "Express Tire & Brake",
    category: "automotive",
    location: "Chicago, IL",
    email: "service@expresstire.com",
    phone: "(312) 555-3800",
    website: "www.expresstire.com",
    address: "3500 N Western Ave, Chicago, IL 60618",
    description: "Tires, brakes, and alignments",
  },
  {
    id: "39",
    businessName: "Luxe Nail Bar",
    category: "beauty",
    location: "Las Vegas, NV",
    email: "book@luxenailbar.com",
    phone: "(702) 555-3900",
    website: "www.luxenailbar.com",
    address: "3200 Las Vegas Blvd S, Las Vegas, NV 89109",
    description: "Nail art and gel manicures",
  },
  {
    id: "40",
    businessName: "Community Savings Bank",
    category: "finance",
    location: "Austin, TX",
    email: "service@communitysavings.com",
    phone: "(512) 555-4000",
    website: "www.communitysavings.com",
    address: "100 Congress Ave, Austin, TX 78701",
    description: "Local community bank",
  },
  {
    id: "41",
    businessName: "Code Camp for Kids",
    category: "education",
    location: "San Francisco, CA",
    email: "register@codecampforkids.com",
    phone: "(415) 555-4100",
    website: "www.codecampforkids.com",
    address: "944 Market St, San Francisco, CA 94102",
    description: "Coding and robotics workshops",
  },
  {
    id: "42",
    businessName: "Harbor View Hotel",
    category: "hospitality",
    location: "Boston, MA",
    email: "reservations@harborviewhotel.com",
    phone: "(617) 555-4200",
    website: "www.harborviewhotel.com",
    address: "70 Rowes Wharf, Boston, MA 02110",
    description: "Waterfront hotel and events",
  },
  {
    id: "43",
    businessName: "The Steakhouse",
    category: "restaurant",
    location: "Las Vegas, NV",
    email: "dine@thesteakhouse.com",
    phone: "(702) 555-4300",
    website: "www.thesteakhouse.com",
    address: "3799 Las Vegas Blvd S, Las Vegas, NV 89109",
    description: "Prime steaks and fine wine",
  },
  {
    id: "44",
    businessName: "AppWorks Labs",
    category: "technology",
    location: "Miami, FL",
    email: "hello@appworkslabs.com",
    phone: "(305) 555-4400",
    website: "www.appworkslabs.com",
    address: "1001 Brickell Bay Dr, Miami, FL 33131",
    description: "Mobile and web app development",
  },
  {
    id: "45",
    businessName: "Wellness Clinic",
    category: "healthcare",
    location: "Seattle, WA",
    email: "info@wellnessclinic.com",
    phone: "(206) 555-4500",
    website: "www.wellnessclinic.com",
    address: "500 Union St, Seattle, WA 98101",
    description: "Integrative and preventive care",
  },
  {
    id: "46",
    businessName: "Outdoor Gear Co",
    category: "retail",
    location: "Denver, CO",
    email: "orders@outdoorgearco.com",
    phone: "(303) 555-4600",
    website: "www.outdoorgearco.com",
    address: "1416 Platte St, Denver, CO 80202",
    description: "Camping and hiking equipment",
  },
  {
    id: "47",
    businessName: "Beachfront Realty",
    category: "real-estate",
    location: "Los Angeles, CA",
    email: "listings@beachfrontrealty.com",
    phone: "(310) 555-4700",
    website: "www.beachfrontrealty.com",
    address: "1500 Ocean Ave, Santa Monica, CA 90401",
    description: "Beach and coastal properties",
  },
  {
    id: "48",
    businessName: "Reliable Auto Service",
    category: "automotive",
    location: "New York, NY",
    email: "service@reliableauto.com",
    phone: "(718) 555-4800",
    website: "www.reliableauto.com",
    address: "4502 Queens Blvd, Sunnyside, NY 11104",
    description: "ASE-certified mechanics",
  },
  {
    id: "49",
    businessName: "Pure Hair Salon",
    category: "beauty",
    location: "Chicago, IL",
    email: "book@purehairsalon.com",
    phone: "(312) 555-4900",
    website: "www.purehairsalon.com",
    address: "108 N State St, Chicago, IL 60602",
    description: "Cut, color, and styling",
  },
  {
    id: "50",
    businessName: "Peak Financial Group",
    category: "finance",
    location: "Denver, CO",
    email: "info@peakfinancial.com",
    phone: "(303) 555-5000",
    website: "www.peakfinancial.com",
    address: "1700 Lincoln St, Denver, CO 80203",
    description: "Retirement and investment planning",
  },
  {
    id: "51",
    businessName: "Music & Arts Institute",
    category: "education",
    location: "Los Angeles, CA",
    email: "enroll@musicartsinstitute.com",
    phone: "(323) 555-5100",
    website: "www.musicartsinstitute.com",
    address: "800 W 1st St, Los Angeles, CA 90012",
    description: "Music lessons and performing arts",
  },
  {
    id: "52",
    businessName: "Mountain Lodge",
    category: "hospitality",
    location: "Denver, CO",
    email: "stay@mountainlodge.com",
    phone: "(303) 555-5200",
    website: "www.mountainlodge.com",
    address: "1717 Broadway, Denver, CO 80202",
    description: "Rustic mountain lodging",
  },
  {
    id: "53",
    businessName: "Brunch & Co",
    category: "restaurant",
    location: "Seattle, WA",
    email: "reservations@brunchandco.com",
    phone: "(206) 555-5300",
    website: "www.brunchandco.com",
    address: "2200 1st Ave, Seattle, WA 98121",
    description: "All-day brunch and coffee",
  },
  {
    id: "54",
    businessName: "DevOps Pro",
    category: "technology",
    location: "Houston, TX",
    email: "contact@devopspro.io",
    phone: "(713) 555-5400",
    website: "www.devopspro.io",
    address: "1600 Smith St, Houston, TX 77002",
    description: "DevOps consulting and training",
  },
  {
    id: "55",
    businessName: "Pediatric Partners",
    category: "healthcare",
    location: "Boston, MA",
    email: "appointments@pediatricpartners.com",
    phone: "(617) 555-5500",
    website: "www.pediatricpartners.com",
    address: "300 Longwood Ave, Boston, MA 02115",
    description: "Pediatric primary care",
  },
  {
    id: "56",
    businessName: "Tech Depot",
    category: "retail",
    location: "Phoenix, AZ",
    email: "sales@techdepot.com",
    phone: "(602) 555-5600",
    website: "www.techdepot.com",
    address: "140 N Central Ave, Phoenix, AZ 85004",
    description: "Computers and electronics",
  },
  {
    id: "57",
    businessName: "Downtown Living",
    category: "real-estate",
    location: "Chicago, IL",
    email: "info@downtownliving.com",
    phone: "(312) 555-5700",
    website: "www.downtownliving.com",
    address: "233 S Wacker Dr, Chicago, IL 60606",
    description: "Downtown condos and townhomes",
  },
  {
    id: "58",
    businessName: "Apex Collision Center",
    category: "automotive",
    location: "Los Angeles, CA",
    email: "estimates@apexcollision.com",
    phone: "(323) 555-5800",
    website: "www.apexcollision.com",
    address: "4200 Crenshaw Blvd, Los Angeles, CA 90008",
    description: "Auto body and collision repair",
  },
  {
    id: "59",
    businessName: "Balance Yoga Studio",
    category: "beauty",
    location: "Austin, TX",
    email: "classes@balanceyogastudio.com",
    phone: "(512) 555-5900",
    website: "www.balanceyogastudio.com",
    address: "1000 E 41st St, Austin, TX 78751",
    description: "Yoga and meditation classes",
  },
  {
    id: "60",
    businessName: "Trust & Wealth Bank",
    category: "finance",
    location: "Miami, FL",
    email: "private@trustwealthbank.com",
    phone: "(305) 555-6000",
    website: "www.trustwealthbank.com",
    address: "1001 Brickell Bay Dr, Miami, FL 33131",
    description: "Private banking and wealth",
  },
];

export const DEFAULT_TABLE_COLUMNS: TableColumnConfig[] = [
  { id: "businessName", label: "Business Name", visible: true },
  { id: "category", label: "Category", visible: true },
  { id: "location", label: "Location", visible: true },
  { id: "email", label: "Email", visible: true },
  { id: "phone", label: "Phone", visible: true },
  { id: "website", label: "Website", visible: false },
  { id: "address", label: "Address", visible: false },
  { id: "description", label: "Description", visible: false },
];
