import type { Lead, TableColumnConfig } from "@/types";

export const LEAD_STATUSES = [
  { value: "rejected", label: "Rejected" },
  { value: "booked", label: "Booked" },
  { value: "closed", label: "Closed" },
  { value: "voicemail", label: "Voicemail" },
  { value: "open", label: "Open" },
  { value: "waiting", label: "Waiting" },
  { value: "does-not-exist", label: "Does not exist" },
  { value: "waiting-plus", label: "Strong" },
] as const;

export const CATEGORIES = [
  { value: "restaurant", label: "Restaurant" },
  { value: "retail", label: "Retail" },
  { value: "healthcare", label: "Healthcare" },
  { value: "technology", label: "Technology" },
  { value: "real-estate", label: "Real Estate" },
  { value: "education", label: "Education" },
  { value: "finance", label: "Finance" },
  { value: "hospitality", label: "Hospitality" },
  { value: "automotive", label: "Automotive" },
  { value: "beauty", label: "Beauty & Wellness" },
] as const;

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    businessName: "Bella Vista Restaurant",
    category: "restaurant",
    location: "New York, NY",
    email: "info@bellavista.com",
    phone: "(212) 555-0101",
    website: "www.bellavista.com",
    address: "123 Main St, New York, NY 10001",
    description: "Italian fine dining restaurant",
  },
  {
    id: "2",
    businessName: "Tech Solutions Inc",
    category: "technology",
    location: "San Francisco, CA",
    email: "contact@techsolutions.com",
    phone: "(415) 555-0202",
    website: "www.techsolutions.com",
    address: "456 Market St, San Francisco, CA 94102",
    description: "Enterprise software solutions",
  },
  {
    id: "3",
    businessName: "Green Leaf Medical Center",
    category: "healthcare",
    location: "Los Angeles, CA",
    email: "info@greenleafmedical.com",
    phone: "(310) 555-0303",
    website: "www.greenleafmedical.com",
    address: "789 Sunset Blvd, Los Angeles, CA 90028",
    description: "Primary care and specialty services",
  },
  {
    id: "4",
    businessName: "Urban Fashion Boutique",
    category: "retail",
    location: "Chicago, IL",
    email: "hello@urbanfashion.com",
    phone: "(312) 555-0404",
    website: "www.urbanfashion.com",
    address: "321 State St, Chicago, IL 60601",
    description: "Trendy clothing and accessories",
  },
  {
    id: "5",
    businessName: "Coastal Realty Group",
    category: "real-estate",
    location: "Miami, FL",
    email: "info@coastalrealty.com",
    phone: "(305) 555-0505",
    website: "www.coastalrealty.com",
    address: "654 Ocean Dr, Miami, FL 33139",
    description: "Luxury real estate services",
  },
  {
    id: "6",
    businessName: "Metro Auto Repair",
    category: "automotive",
    location: "Houston, TX",
    email: "service@metroauto.com",
    phone: "(713) 555-0606",
    website: "www.metroauto.com",
    address: "987 Highway 59, Houston, TX 77002",
    description: "Full-service auto repair shop",
  },
  {
    id: "7",
    businessName: "Zen Spa & Wellness",
    category: "beauty",
    location: "Seattle, WA",
    email: "bookings@zenspa.com",
    phone: "(206) 555-0707",
    website: "www.zenspa.com",
    address: "147 Pine St, Seattle, WA 98101",
    description: "Holistic wellness and spa services",
  },
  {
    id: "8",
    businessName: "Downtown Diner",
    category: "restaurant",
    location: "Boston, MA",
    email: "info@downtowndiner.com",
    phone: "(617) 555-0808",
    website: "www.downtowndiner.com",
    address: "258 Tremont St, Boston, MA 02116",
    description: "Classic American diner",
  },
  {
    id: "9",
    businessName: "City Bank & Trust",
    category: "finance",
    location: "New York, NY",
    email: "contact@citybank.com",
    phone: "(212) 555-0909",
    website: "www.citybank.com",
    address: "741 Wall St, New York, NY 10005",
    description: "Personal and business banking",
  },
  {
    id: "10",
    businessName: "Learning Academy",
    category: "education",
    location: "Austin, TX",
    email: "admissions@learningacademy.com",
    phone: "(512) 555-1010",
    website: "www.learningacademy.com",
    address: "852 Congress Ave, Austin, TX 78701",
    description: "Private K-12 education",
  },
];

export const DEFAULT_TABLE_COLUMNS: TableColumnConfig[] = [
  { id: "businessName", label: "Business Name", visible: true },
  { id: "category", label: "Category", visible: true },
  { id: "location", label: "Location", visible: true },
  { id: "email", label: "Email", visible: true },
  { id: "phone", label: "Phone", visible: true },
  { id: "website", label: "Website", visible: false },
  { id: "address", label: "Address", visible: false },
  { id: "description", label: "Description", visible: false },
  { id: "socialMedia", label: "Social Media", visible: false },
];
